/**
 * blueprint-config.ts
 *
 * AUTO-GENERATED by Micro-SaaS Launcher.
 * Do not edit manually — re-run the generator to update.
 *
 * Blueprint : feedback_board
 * Generated : 2026-04-17T15:16:59.389Z
 * Project ID: proj_demo_inferred
 */

export type FieldDef = { name: string; type: string };

export type SectionConfig = {
  type: string;
  title?: string;
  subtitle?: string;
  cta_text?: string;
  cta_link?: string;
  table?: string;
  fields?: FieldDef[];
};

export type PageConfig = {
  name: string;
  type: string;
  sections: SectionConfig[];
};

export const APP_NAME = "Feedback Board";
export const PROJECT_ID = "proj_demo_inferred";
export const TEMPLATE = "content-site";
export const MODULES: string[] = [];
export const ENABLE_AUTH = false;
export const TABLE_PREFIX = "feedback_board";

export function dbTableName(rawTableName: string): string {
  return `${TABLE_PREFIX}_${rawTableName.trim().toLowerCase().replace(/[^a-z0-9_]/g, "_")}`;
}

export const navPages: Array<{ name: string; type: string }> = [
  {
    "name": "Landing",
    "type": "landing"
  },
  {
    "name": "Submit",
    "type": "form"
  },
  {
    "name": "Reviews",
    "type": "list"
  },
  {
    "name": "Dashboard",
    "type": "dashboard"
  }
];

export const pageConfigs: Record<string, PageConfig> = {
  "submit": {
    "name": "Submit",
    "type": "form",
    "sections": [
      {
        "type": "form",
        "cta_text": "Submit Feedback",
        "table": "feedback",
        "fields": [
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "description",
            "type": "text"
          },
          {
            "name": "category",
            "type": "text"
          }
        ]
      }
    ]
  },
  "reviews": {
    "name": "Reviews",
    "type": "list",
    "sections": [
      {
        "type": "table",
        "title": "All Feedback",
        "table": "feedback",
        "fields": [
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "description",
            "type": "text"
          },
          {
            "name": "category",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          }
        ]
      }
    ]
  },
  "dashboard": {
    "name": "Dashboard",
    "type": "dashboard",
    "sections": [
      {
        "type": "table",
        "title": "Manage Feedback",
        "table": "feedback",
        "fields": [
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "description",
            "type": "text"
          },
          {
            "name": "category",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          }
        ]
      },
      {
        "type": "table",
        "title": "All Votes",
        "table": "votes",
        "fields": [
          {
            "name": "feedback_id",
            "type": "uuid"
          },
          {
            "name": "user_id",
            "type": "uuid"
          }
        ]
      }
    ]
  }
};

export const dashboardTables: Array<{ table: string; fields: FieldDef[] }> = [
  {
    "table": "feedback",
    "fields": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "category",
        "type": "text"
      },
      {
        "name": "status",
        "type": "text"
      }
    ]
  },
  {
    "table": "votes",
    "fields": [
      {
        "name": "feedback_id",
        "type": "uuid"
      },
      {
        "name": "user_id",
        "type": "uuid"
      }
    ]
  }
];
