/**
 * blueprint-config.ts
 *
 * AUTO-GENERATED by the Micro-SaaS Launcher generator.
 * Do not edit manually — re-run the generator to update.
 *
 * This file is the single source of truth for your blueprint config in the
 * generated Next.js app. The generator fills these constants from your
 * blueprint JSON at code-generation time.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type FieldDef = {
  name: string;
  type: string;
};

export type SectionConfig = {
  type: "hero" | "form" | "table" | "cards" | string;
  title?: string;
  subtitle?: string;
  cta_text?: string;
  cta_link?: string;
  table?: string;
  fields?: FieldDef[];
};

export type PageConfig = {
  name: string;
  type: "landing" | "form" | "dashboard" | "list" | "detail" | string;
  sections: SectionConfig[];
};

// ─── Generator Fill Targets ───────────────────────────────────────────────────

/**
 * The project name (human-readable). Filled by generator from blueprint.project_name
 */
export const APP_NAME = "Micro SAAS";

/**
 * The Supabase project_id used to scope all table queries.
 * Filled by generator from the project record in the launcher DB.
 */
export const PROJECT_ID = "PLACEHOLDER_PROJECT_ID";

/**
 * Nav pages — used by Navbar to generate navigation links.
 * Filled by generator from blueprint.pages.
 */
export const navPages: Array<{ name: string; type: string }> = [
  { name: "Home", type: "landing" },
  { name: "Dashboard", type: "dashboard" },
];

/**
 * Page configs — keyed by slug (URL segment).
 * Generated from blueprint.pages[] (excluding the landing page).
 *
 * The dynamic route handler [dynamic_page]/page.tsx reads this to
 * determine what sections to render for each URL.
 *
 * Example entry populated by the generator:
 * {
 *   feedback: {
 *     name: "Feedback",
 *     type: "form",
 *     sections: [{ type: "form", table: "feedback", fields: [...] }]
 *   }
 * }
 */
export const pageConfigs: Record<string, PageConfig> = {
  // GENERATOR_PLACEHOLDER — do not remove this comment
  example: {
    name: "Example",
    type: "form",
    sections: [
      {
        type: "form",
        table: "example",
        fields: [
          { name: "title", type: "text" },
          { name: "description", type: "text" },
        ],
      },
    ],
  },
};

/**
 * Dashboard tables — AutoCRUD instances shown on the /dashboard page.
 * Filled by generator from pages with type === "dashboard".
 */
export const dashboardTables: Array<{ table: string; fields: FieldDef[] }> = [
  {
    table: "example",
    fields: [
      { name: "title", type: "text" },
      { name: "description", type: "text" },
    ],
  },
];
