/**
 * blueprint-config.ts
 *
 * AUTO-GENERATED by Micro-SaaS Launcher.
 * Do not edit manually — re-run the generator to update.
 *
 * Blueprint : demo_content_site
 * Generated : 2026-04-17T15:33:07.401Z
 * Project ID: proj_content_demo
 */

export type FieldDef = { name: string; type: string };

export type SectionConfig = {
  type: string;
  title?: string;
  subtitle?: string;
  cta_text?: string;
  cta_link?: string;
  table?: string;
  fields?: FieldDef[];
};

export type PageConfig = {
  name: string;
  type: string;
  sections: SectionConfig[];
};

export const APP_NAME = "Demo Content Site";
export const PROJECT_ID = "proj_content_demo";
export const TEMPLATE = "content-site";
export const MODULES: string[] = [
  "auth"
];
export const ENABLE_AUTH = true;
export const TABLE_PREFIX = "demo_content_site";

export function dbTableName(rawTableName: string): string {
  return `${TABLE_PREFIX}_${rawTableName.trim().toLowerCase().replace(/[^a-z0-9_]/g, "_")}`;
}

export const navPages: Array<{ name: string; type: string }> = [];

export const pageConfigs: Record<string, PageConfig> = {};

export const dashboardTables: Array<{ table: string; fields: FieldDef[] }> = [];
